### ISSUE TITLE
Doesnt Suppor more than 1 database

### ISSUE THREAD

**Issue by iballan** [pavel163/ProbeTools#1]
I tried to show more than one database:

```
            Probetools.setSQLiteOpenHelper(new MyDb1(this));
            Probetools.setSQLiteOpenHelper(new MyDb2(this));
            Probetools.setSQLiteOpenHelper(new MyDb2(this));
```

it shows only the last database.

**Comment by pavel163** [comment]
in the next release I will support multiple databases

**Comment by pavel163** [comment]
New release supports more than 1 database
`Probetools.putDatabase(DB_NAME_1, DB_VERSION_1);
Probetools.putDatabase(DB_NAME_2, DB_VERSION_2);`
